### ISSUE TITLE
module build failed: error: posts.service.ts (11,3)

### ISSUE THREAD

**Issue by gh0st** [gangachris/ng2-mean#1]
Running `npm run build` just before the end of this tutorial generates this error

angular-cli: 1.0.0-beta.22-1
node: 6.9.2
os: linux x64

```
ERROR in ./src/app/posts.service.ts
Module build failed: Error: /home/chad/Developer/issac/src/app/posts.service.ts (11,3): Return type of
public method from exported class has or is using name 'Observable' from external module "/home/chad/De
veloper/issac/node_modules/rxjs/Observable" but cannot be named.)
    at _checkDiagnostics (/home/chad/Developer/issac/node_modules/@ngtools/webpack/src/loader.js:115:15
)
    at /home/chad/Developer/issac/node_modules/@ngtools/webpack/src/loader.js:140:17
 @ ./src/app/posts/posts.component.ts 11:0-48
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
```

**posts.component.ts**
```
import { Component, OnInit } from '@angular/core';
import { PostsService } from '../posts.service';

@Component({
  selector: 'app-posts',
  templateUrl: './posts.component.html',
  styleUrls: ['./posts.component.css']
})
export class PostsComponent implements OnInit {
  // instantiate posts to an empty array
  posts: any = [];

  constructor(private postsService: PostsService) { }

  ngOnInit() {
    this.postsService.getAllPosts().subscribe(posts => {
      this.posts = posts;
    });
  }

}
```

**posts.service.ts**
```
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import 'rxjs/add/operator/map';

@Injectable()
export class PostsService {

  constructor(private http: Http) { }

  // get all posts from the api
  getAllPosts() {
    return this.http.get('/api/posts')
      .map(res => res.json());
  }

}
```

**Comment by gangachris** [comment]
Hi @gh0st 

I could not reproduce the problem. Could you however try adding `import { Observable } from 'rxjs';` in the **posts.service.ts**
```typescript
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import { Observable } from 'rxjs'; // Add this 
import 'rxjs/add/operator/map';

@Injectable()
export class PostsService {

  constructor(private http: Http) { }

  // get all posts from the api
  getAllPosts() {
    return this.http.get('/api/posts')
      .map(res => res.json());
  }

}
```

**Comment by gh0st** [comment]
That seemed to have done the trick. Thank you @gangachris!!
